services:
  - type: web
    name: doodstream-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: DOODSTREAM_API_KEY
        sync: false
      - key: ADMIN_IDS
        sync: false
    plan: free
    autoDeploy: true
